# Generated by Django 4.2.1 on 2024-02-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['-time_create'], name='homepage_ca_time_cr_8b34e0_idx'),
        ),
    ]
