# Generated by Django 4.2.1 on 2024-02-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_owner_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='c_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
